Made a common interface for MvPlugin
Minevictus/MV-Util pull request #2
Opened 2020-05-09 14:54 UTC by NahuLD

TODO:
- [ ] Move messaging channel interfaces to common
- [ ] Make utility for databases

2020-05-09 21:43 UTC, NahuLD commented
I don't know if I'm too happy with that. Didn't want to change too much things

2020-05-10 18:52 UTC, Proximyst requested changes

2020-05-10 18:52 UTC, Proximyst commented on bungee/src/main/java/us/minevict/mvutil/bungee/MvPlugin.java
> +  public boolean load()
Use a default method in the parent interface instead.

2020-05-10 18:52 UTC, Proximyst commented on bungee/src/main/java/us/minevict/mvutil/bungee/MvPlugin.java
> +  public boolean enable()
Use a default method in the parent interface instead.

2020-05-10 18:52 UTC, Proximyst commented on bungee/src/main/java/us/minevict/mvutil/bungee/MvPlugin.java
> +  public void disable()
Use a default method in the parent interface instead.

2020-05-10 18:52 UTC, Proximyst commented on bungee/src/main/java/us/minevict/mvutil/bungee/MvPlugin.java
> +  public BungeeCommandManager constructAcf() {
This is an implementation detail and should not be public by a parent interface.

2020-05-10 18:52 UTC, Proximyst commented on bungee/src/main/java/us/minevict/mvutil/bungee/MvPlugin.java
> +  public final void registerCommands(boolean force, @NotNull BaseCommand... commands) {
Forcing is a platform detail and should therefore not be common as it is not common in ACF.

2020-05-10 18:52 UTC, Proximyst commented on bungee/src/main/java/us/minevict/mvutil/bungee/MvPlugin.java
> +  public <P, C extends IPacketChannel<P, ?>> C packetChannel(@NotNull C channel) {
Require a `PacketChannel<P>` here instead.

2020-05-10 18:52 UTC, Proximyst commented on bungee/src/main/java/us/minevict/mvutil/bungee/utils/DatabaseUtils.java
> + * Utilities ported over from Aikar's Bukkit IDB to manage DB creation for Bungee on a simpler manner.
`in a simpler manner`.

2020-05-10 18:52 UTC, Proximyst commented on common/src/main/java/us/minevict/mvutil/common/IMvPlugin.java
> +    boolean load() throws Exception;
```java
default boolean load() throws Exception {
    return true;
}
```

2020-05-10 18:52 UTC, Proximyst commented on common/src/main/java/us/minevict/mvutil/common/IMvPlugin.java
> +    boolean enable() throws Exception;
```java
default boolean enable() throws Exception {
    return true;
}
```

2020-05-10 18:52 UTC, Proximyst commented on common/src/main/java/us/minevict/mvutil/common/IMvPlugin.java
> +    void disable() throws Exception;
```java
default void disable() throws Exception {
}
```

2020-05-10 18:52 UTC, Proximyst commented on common/src/main/java/us/minevict/mvutil/common/IMvPlugin.java
> +    void shutdownSafely(boolean options);
Implementation detail and should not be public to other plugins.

2020-05-10 18:52 UTC, Proximyst commented on common/src/main/java/us/minevict/mvutil/common/IMvPlugin.java
> +    CM constructAcf();
Implementation detail, see above.

2020-05-10 18:52 UTC, Proximyst commented on common/src/main/java/us/minevict/mvutil/common/IMvPlugin.java
> +    MinevictusUtilsPlatform<?, CM> getMvUtil();
Wouldn't just having an extra generic for the platform be better?

2020-05-10 18:52 UTC, Proximyst commented on common/src/main/java/us/minevict/mvutil/common/IMvPlugin.java
> +    Database constructDatabase();
Implementation detail.

2020-05-10 18:52 UTC, Proximyst commented on bungee/src/main/java/us/minevict/mvutil/bungee/MvPlugin.java
> +  public void shutdownSafely() {
Implementation detail.

2020-05-10 18:52 UTC, Proximyst commented on bungee/src/main/java/us/minevict/mvutil/bungee/MvPlugin.java
> +  public void shutdownSafely(boolean options) {
Implementation detail.

2020-05-10 18:52 UTC, Proximyst commented on bungee/src/main/java/us/minevict/mvutil/bungee/MvPlugin.java
> +  private String databaseName = getName().replace(" ", "_").toLowerCase();
`getName()` is not guaranteed to be populated with a value at this time. Do this in `#onLoad` using the `PluginDescriptionFile`.

2020-05-10 18:52 UTC, Proximyst commented on common/src/main/java/us/minevict/mvutil/common/IMvPlugin.java
> +     * <p>
Remember to close this.

2020-05-10 18:52 UTC, Proximyst commented on spigot/src/main/java/us/minevict/mvutil/spigot/MvPlugin.java
> +  private String databaseName = getName().replace(" ", "_").toLowerCase();
`getName()` is not guaranteed to be populated yet. Do this in `#onLoad`.

2020-05-10 19:21 UTC, NahuLD commented on common/src/main/java/us/minevict/mvutil/common/channel/IPacketChannel.java
> +  boolean sendPacket(RCV receiver, P packet);
I forgot to mark the receiver as NotNull here

2020-05-10 19:30 UTC, NahuLD commented
All done, mark the requested changes as done and we merge :1234:

2020-05-10 19:32 UTC, Proximyst approved these changes
LGTM. Make sure to push a new tag!

2020-05-10 19:32 UTC, merged